Repository DiegoArruda/API-4-Delivery, pull requests merged in 2023-04, with the labels that each got.

#2 CRUD de pedidos completo e CRUD de entregadores quase completo
  .gitignore
  database/database.js
  database/entregador.js
  database/pedido.js
  index.js
  package-lock.json
  package.json
  routes/entregadores.js
  routes/pedidos.js
Labels: enhancement

#3 Dev
  database/entregador.js
  database/pedido.js
  delivery_app.postman_collection.json
  routes/entregadores.js
  routes/pedidos.js
Labels: enhancement

#5 Swagger
  index.js
  package-lock.json
  package.json
  routes/entregadores.js
  routes/pedidos.js
  swagger.json
Labels: bug, documentation, enhancement

#8 Correção da documentação de Pedidos
  routes/entregadores.js
  routes/pedidos.js
Labels: bufix

#9 ajustando
  routes/pedidos.js
Labels: documentation, enhancement

#11 Correção de bug
  index.js
Labels: bufix
